version: "1.0"
stages:
  - precheck
  - clone
  - build
  - notify
steps:
  checkShoutrrrLatestVersion:
    title: Check latest shoutrrr version
    type: freestyle
    stage: precheck
    arguments:
      image: alpine:latest
      commands:
        - apk add jq curl
        - export SHOUTRRR_VERSION=$(curl
          https://api.github.com/repos/containrrr/shoutrrr/releases/latest | jq -r .name | tr -d v)
        - cf_export SHOUTRRR_VERSION
        
  checkIfDockerImageExists:
    title: Check if my docker repo has image
    stage: precheck
    fail_fast: false
    arguments:
      image: mprokopi/shoutrrr:${{SHOUTRRR_VERSION}}
      commands:
        - shoutrrr -v      
    hooks:
      on_success:
        exec:
          image: docker.io/mprokopi/shoutrrr:latest
          environment:
            - TITLE=Codefresh CD - ${{CF_PIPELINE_NAME}}
          commands:
            - |-
              shoutrrr send --url "telegram://$TG_NOTIFICATION_TOKEN@telegram?chats=$TG_CHAT_ID&notification=no&preview=No&ParseMode=HTML&Title=$TITLE" --message \
              "✅ Новий образ <b>shoutrrr</b> не потрібен."
              
  cloneRepo:
    title: "Cloning repository"
    type: "git-clone"
    repo: "johnatank/shoutrrr-docker-image"
    revision: main
    git: "github"
    stage: "clone"
    when:
      condition:
        all:
          checkIfDockerImageExistsFailure: steps.checkIfDockerImageExists.result == 'failure'
          
  dockerImageBuild:
    type: build
    title: Building docker image
    stage: build
    arguments:
      build_arguments:
      - SHOUTRRR_VERSION=${{SHOUTRRR_VERSION}}
      working_directory: '${{cloneRepo}}'
      dockerfile: Dockerfile
      image_name: mprokopi/shoutrrr
      tag: '${{SHOUTRRR_VERSION}}'
      tags:
        - latest
      registry: my-docker-hub
    when:
      condition:
        all:
          checkIfDockerImageExistsFailure: steps.checkIfDockerImageExists.result == 'failure'
    hooks:
      on_fail:
        exec:
          image: docker.io/mprokopi/shoutrrr:latest
          environment:
            - TITLE=Codefresh CD - ${{CF_PIPELINE_NAME}}
          commands:
            - |-
              shoutrrr send --url "telegram://$TG_NOTIFICATION_TOKEN@telegram?chats=$TG_CHAT_ID&notification=no&preview=No&ParseMode=HTML&Title=$TITLE" --message \
              "❗️Упс. Сталася помилка при збірці образу <b>shoutrrr</b>. 
              Переглянути статус збірки можна за <a href=\"${{CF_BUILD_URL}}\">посиланням</a>."
      
  notifyOnSuccess:
    title: Notify on success of pipeline
    type: freestyle
    stage: notify
    arguments:
      image: docker.io/mprokopi/shoutrrr:latest
      environment:
        - TITLE=Codefresh CD - ${{CF_PIPELINE_NAME}}
      commands:
        - |-
          shoutrrr send --url "telegram://$TG_NOTIFICATION_TOKEN@telegram?chats=$TG_CHAT_ID&notification=no&preview=No&ParseMode=HTML&Title=$TITLE" --message \
          "✅ Збірка образу <b>shoutrrr</b> завершена.  
          Переглянути статус збірки можна за <a href=\"${{CF_BUILD_URL}}\">посиланням</a>."
    when:
      condition:
        all:
          dockerImageBuildStatus: steps.dockerImageBuild.result == 'success'